### ISSUE TITLE
The tarball of KDE (20160212) didn't include efivar.

### ISSUE THREAD

**Issue by RedL0tus** [AOSC-Dev/aosc-os#2]
The tarball of KDE (20160212) didn't include **efivars**.

When running "grub-install --target=**x86_64-efi** " the **efibootmgr** will return a error about that it can't find a file which provided by **efivars**.

原谅我那 *\* 的英语。

就是说20160212的KDE版的tarball不带efivars导致安装GRUB ( target=x86_64-efi ) 时报错，找不到一个.so的文件（名字记不清了

**Comment by Artoria2e5** [comment]
INVALID.

efivars aren't supposed to be packed in the tarball. How did you boot the system?

**Comment by Artoria2e5** [comment]
And there should not be any ELF SOs in efivars.

(Hey, did you forget to mount --bind?

**Comment by Artoria2e5** [comment]
upd: package 'efivars'

**Comment by RedL0tus** [comment]
I mean the PACKAGE "efivars"

**Comment by MingcongBai** [comment]
Seemingly a package fault back when `efivars` was not updated. My bad.

**Comment by MingcongBai** [comment]
Nope, I was horribly wrong, `efivars` and `efivar` are two very different packages.

**Comment by MingcongBai** [comment]
Nonetheless, tarballs will be re-rolled today.

**Comment by MingcongBai** [comment]
`efivar` 0.21, bad, a totally incomplete package.
`efivar` 0.23, good.

**Comment by liushuyu** [comment]
So why not closing this ?

**Comment by MingcongBai** [comment]
Yep, they are all uploaded as 20160220 revision. Closing.
