### ISSUE TITLE
Article req: NM Random MAC

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os#7]
This should be as simple as "if you are using blah blah adapters and find your NM failing, then run this echo."

**Comment by MingcongBai** [comment]
A workaround solution was proposed by @Icenowy in `staging` as:

- https://github.com/AOSC-Dev/aosc-os-abbs/commit/30a6e0a9ae10292b3ba8d928246a195f4d72d0ec
- https://github.com/AOSC-Dev/aosc-os-abbs/commit/098a3ee08eb9569ceec6585e5fc60ee7b69ccdcf

I will write up a wiki page.

**Comment by Artoria2e5** [comment]
Patchy hints:

* randomize config (boolean) seen at https://github.com/NetworkManager/NetworkManager/blob/be813707f00050c39470ca421463da4c34ed27e4/src/devices/wifi/nm-device-wifi.c#L1104
* scanned by nm_device_hw_addr_set?
