### ISSUE TITLE
Suggestions for improving AOSC Wiki and Tarballs v20180128.

### ISSUE THREAD

**Issue by bobby285271** [AOSC-Dev/aosc-os#8]
非常期待新的 Tarball，于是从十月等到十一月，从十一月等到十二月，从十二月等到一月...😂

**Comment by MingcongBai** [comment]
实在非常抱歉…… 目前在各个架构的版本对齐上有点进度滞后。不过 amd64 的 tarball 一定会在本月出来。

**Comment by bobby285271** [comment]
@MingcongBai 
看到新版本啦！旅游完就试试.

根据 https://aosc.io/news/4766-new-tarball-releases
> The tarballs no longer come with a default `aosc` user, or the `users` group occupying the 1000 UID and GID, respectively. You would have to create your own user, as discussed in the Wiki.

所以是说要自己用 `useradd` 创建用户（而不是修改 `aosc` 的用户名）？
然后那个 `users` 组默认不存在？
可以把 Wiki 的相关内容改了... 不然误导萌新😄
例如这样：

User, and Post-installation Configuration
-----------------------------------------

The tarballs doesn't come with a default user and `root` user is disabled, you would have to create your own account before you reboot into AOSC OS - while leaving the password empty for the `root` user - you can always use sudo for your superuser needs.

### Add a user

To add a new user `aosc`, use the `useradd` command: 

```
# useradd -m -G wheel -s /bin/bash aosc
```

### Setting the password

Although it is not required to protect the newly created user `aosc` with a password, it is highly recommend to do so: 

```
# passwd aosc
```

（如果要更新的话，还有一个开头的导航也要更新）
[这是中文版的：](https://github.com/AOSC-Dev/aosc-os/wiki/x86_64-%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97#%E7%BB%99-aosc-%E5%85%88%E7%94%9F%E9%87%8D%E6%96%B0%E8%B5%B7%E4%B8%AA%E5%90%8D%E5%AD%97)

用户自定义设置
-----------------------------------------

所有的 tarballs 都不带有默认账户且 `root` 账户默认被禁用，你需要在重启进入 AOSC OS 之前创建一个账户并保留 `root` 密码为空 - 你仍然可以用 sudo 来获取超级用户（root）权限。

### 创建用户

使用 `useradd` 命令添加用户 `aosc`： 

```
# useradd -m -G wheel -s /bin/bash aosc
```

### 设置密码

通过下列命令为用户 `aosc` 设置密码，虽然不是必须的，还是强烈建议设置密码：

```
# passwd aosc
```

**Comment by MingcongBai** [comment]
没错。

**Comment by bobby285271** [comment]
@MingcongBai 呀你上线得太快... 那我直接按照上面的编辑啦？

**Comment by MingcongBai** [comment]
没问题，我几小时后回头检查下，多谢啦。

**Comment by bobby285271** [comment]
https://github.com/AOSC-Dev/aosc-os-arm-bsps/wiki
这里还有两篇安装指南，不知道需不需要调整
其它架构 估计 大概 可能 或许 都改好了吧😂
~~反正有啥问题你也能及时改过来的~~

**Comment by MingcongBai** [comment]
嗯，我会把这些更改移植到 wiki.aosc.io，这个站点差不多可以上线了…… 还差点基本页面没写好

**Comment by bobby285271** [comment]
@MingcongBai 
对了，一觉醒来才记起来... 好像只有 x86_64 是发布了新的 tarball
其它的好像还没发布来着...😂 怕是超前了...
其它架构的等发布了再移植吧... 如果有必要，这边也可以先回退回去...
不过按理来说一周后也应该发布了吧...

**Comment by MingcongBai** [comment]
其他架构目前还需要同步下软件包的版本，可能还需要一两个星期，尽可能春节期间搞定吧……

**Comment by bobby285271** [comment]
嗯... 其实我是不建议用底下划横线的方式来设定第一二级标题的... 在不同的情况下会有不同的结果的...
![screenshot_2018-02-09-18-20-58-627_com ryeeeeee markdownx](https://user-images.githubusercontent.com/20080233/36026029-45dec0e4-0dd0-11e8-9d6a-63e6bde24110.png)
![screenshot_2018-02-09-18-20-55-420_com ryeeeeee markdownx](https://user-images.githubusercontent.com/20080233/36026035-5035fd8c-0dd0-11e8-9e33-c34d7aa8abce.png)

**Comment by bobby285271** [comment]
感觉在一个关着的 issue 里面说话有点怪... 
https://wiki.aosc.io/users/installation/amd64 那里也改了，其它地方我还没碰，等新 tarball 出来再说。

**Comment by bobby285271** [comment]
@MingcongBai 
装上了，体验不错。
KDE 的 Tarball 建议把 `kcm-fcitx` 加上... 毕竟 Fcitx 已经被预装了...

**Comment by MingcongBai** [comment]
装是装上了的…… 只是没有默认打开，会考虑这个建议的，多谢。另外这种非 issue 相关的回复最好还是来讨论群组说，否则会偏题。这个 issue 先关了。

**Comment by LionNatsu** [comment]
@MingcongBai 抱歉在关闭的 issue 里继续回复。kcm-fcitx 没有预装。我同学的新 KDE 环境今天确认了这一点（1月 tarball）。

转移到新的 issue 中。
