### ISSUE TITLE
Make an X keyboard layout for pinyin

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os#9]
We should probably steal some code from us-international to make a layout for easily typing Hanyu Pinyin. Here's a quick plan:

* Use `!` `@` `#` `$` for dead keys. Each of them correspond to a tone.
  * If we are doing it the `altgr-intl` (trigger dead key only on altgr) mode, we can use 1 2 3 4.
* When doing dead key composion on vowels, assume `v` to be `ü`.
* Assign `AltGr+u` or `AltGr+v` to `ü`.

**Comment by Artoria2e5** [comment]
```
// Pinyin Keyboard for convenience, in the style of altgr-intl
//
// Chinese speakers and learners often find it hard to type Hanyu Pinyin
// with all its tones and ü. This file defines an altgr-intl-like behavior.
//
// Number row keys 1 2 3 4 are defined as dead-keys for the tones.
// They correspond to the four tones in Hanyu Pinyin.
//
// To generate a raw ü, use AltGr + v.
// V is used instead of ü for tones.
//
// This file should be used with an appropriate XCompose file with
// definitons for dead_{macron,acute,caron,grave} + a/e/i/o/u.
// en_US.UTF-8's Compose may be used for this purpose.
// --Mingye Wang <arthur200126@gmail.com>

artial alphanumeric_keys
xkb_symbols "altgr-pinyin" {

   include "us(basic)"
   name[Group1]= "Chinese (Pinyin numeric tone dead keys)";

   key <AE01> { [	   1,	exclam,		dead_macron,	   macron ]	};
   key <AE02> { [	   2,	at,		dead_acute,	    acute ]	};
   key <AE03> { [	   3,	numbersign,	dead_caron,	    caron ]	};
   key <AE04> { [	   4,	dollar,		dead_grave,	    grave ]	};
   key <AB04> {	[	   v,	V,		udiaeresis,	Udiaeresis]	};

   include "level3(ralt_switch)"
};
```

**Comment by Artoria2e5** [comment]
We still need to complete the XCompose segment. Put in compositions for udiaeresis/Udiaeresis and add some `Multi_Key` versions of the compositions above.

**Comment by Artoria2e5** [comment]
Oh we actually don't need one as en_US.UTF-8 already provides them. Let's just make zh_CN.UTF-8's Compose a big `Include`.

**Comment by MingcongBai** [comment]
Closing. Should interest arise again, please post to [aosc-os-abbs](https://github.com/AOSC-Dev/aosc-os-abbs) instead.
